version: "3.8"

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=godorodb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
  spring-app:
    build: ./backend-rest
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/godorodb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=mysecretpassword
    networks:
      - app-network

  react-app:
    build: ./frontend-react
    ports:
      - "3000:80"
    depends_on:
      - spring-app
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
